apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  namespace: hw11-monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: loki-storage
  hostPath:
    path: /mnt/data/loki
