apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: hw11-monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
    [OUTPUT]
        Name        loki
        Match       *
        Host        loki
        Port        3100
        Labels      job=nginx-logs
