apiVersion: v1
kind: PersistentVolume
metadata:
  name: hw11-pv
  namespace: hw11
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: "/mnt/data/busybox-logs"

  